version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: crypto_dashboard_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crypto_network

  redis:
    image: redis:7-alpine
    container_name: crypto_dashboard_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - crypto_network

  # Optional: Redis Commander for Redis GUI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: crypto_redis_gui
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - crypto_network

volumes:
  postgres_data:
  redis_data:

networks:
  crypto_network:
    driver: bridge